### ISSUE TITLE
How do you update to new locked revisions?

### ISSUE THREAD

**Issue by kballard** [Shougo/neobundle.vim#413]
When I install a bundle for the first time, if that bundle is listed in my `NeoBundle.lock`, it checks out the locked revision. But I've never been able to figure out how to update to a new locked revision. The only command that seems to care about the revision locks is `:NeoBundleInstall`, but that won't do anything if the bundle is already installed. And `:NeoBundleUpdate` will attempt to update to the latest version instead of the locked revision (which makes sense).

What I'd expect is for `:NeoBundleInstall` to update all bundles to match their locked revisions (but not detaching the HEAD if the current branch already matches that revision). Similarly, I'd expect `:NeoBundleInstall someBundle` to not rewrite the lockfile to specify older revisions, if my current bundles are out-of-date (right now it rewrites the whole lockfile with all the current revisions).

**Comment by Shougo** [comment]
You should edit NeoBundle.lock file and use `:NeoBundleReinstall someBundles` command.

**Comment by kballard** [comment]
Doesn't that delete and re-checkout the whole repo? I don't want to do that. I just want to fetch and then checkout the right revision.

Also, I want to update a lot of bundles at once. It's completely unmanageable to do something like that when I have 20 bundles that need updating.

The use-case here is syncing my `NeoBundle.lock` file between two computers. I update my bundles on one computer, and I want to have the other computer update to the same revisions as on the first. That's kind of the whole point of having a lock file, isn't it?

**Comment by Shougo** [comment]
OK.  I get it.
I will fix it.

**Comment by Shougo** [comment]
Implemented.  `:NeoBundleInstall` will update the plugins if NeoBundle.lock is changed.

**Comment by kballard** [comment]
It's progress, but it still has a problem. When installing bundles for the first time that have locked revisions, neobundle will give it a detached HEAD. After updating for your change, `:NeoBundleInstall` appears to invoke `git pull --ff --ff-only && git submodule update --init --recursive` (based on `:NeoBundleLog`). Since these plugins were installed with a detached HEAD, this command will fail, and leave the bundle at its old state. And then at the end, neobundle will write out a new lockfile that contains the current revisions, which means that not only will it fail to update the plugins, if I don't pay attention, I might accidentally check in a lockfile that downgrades my plugins.

What it should be doing if it has a locked revision is running `git fetch origin` and then checking out the new revision.

Ideally, it would be even smarter and check if there's a branch checked out, and if there is, checking if the new revision is reachable from the branch upstream (after `git fetch`). If it is reachable, then update the local branch to point to the new revision (which may mean it's behind upstream, but that's ok). But if the new revision is not reachable from the branch upstream, then switch back to a detached HEAD. In other words, this would keep the current branch checked-out if it makes sense to do so when updating to the new revision, in order to make a future `:NeoBundleUpdate` work. But this is a fair amount of extra work, so I wouldn't blame you if you opted not to do this.

**Comment by kballard** [comment]
That didn't seem to do anything. `:NeoBundleInstall` is still producing the exact same issue:

```
[neobundle/install] Update started: (2015/09/01 13:01:09)
[neobundle/install] ( 1/20): |vimproc.vim| git pull --ff --ff-only && git submodule update --init --recursive
[neobundle/install] ( 2/20): |vim-signify| git pull --ff --ff-only && git submodule update --init --recursive
[neobundle/install] ( 3/20): |vim-fugitive| git pull --ff --ff-only && git submodule update --init --recursive
[neobundle/install] ( 4/20): |rust.vim| git pull --ff --ff-only && git submodule update --init --recursive
[neobundle/install] ( 4/20): |rust.vim| Error
/Users/kevinballard/.vim/neobundle/rust.vim
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

[neobundle/install] ( 5/20): |gitv| git pull --ff --ff-only && git submodule update --init --recursive
[neobundle/install] ( 1/20): |vimproc.vim| Error
/Users/kevinballard/.vim/neobundle/vimproc.vim
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

[neobundle/install] ( 2/20): |vim-signify| Error
/Users/kevinballard/.vim/neobundle/vim-signify
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

[neobundle/install] ( 3/20): |vim-fugitive| Error
/Users/kevinballard/.vim/neobundle/vim-fugitive
You are not currently on a branch. Please specify which
branch you want to merge with. See git-pull(1) for details.

    git pull <remote> <branch>

...
```

**Comment by Shougo** [comment]
Fixed.

**Comment by kballard** [comment]
Sorry, still broken. It's now checking out the latest `master` branch, which doesn't match what's in my lockfile.

**Comment by Shougo** [comment]
> Sorry, still broken. It's now checking out the latest master branch, which doesn't match what's in my lockfile.

Really?  I have tested it and it works.
Please describe the problem in datail.
I don't understand it.

**Comment by kballard** [comment]
On my second machine, I run `:NeoBundleInstall`. It updates all my bundles. When it's done, my `NeoBundle.lock` now has changes in it, and by looking closer, it appears to have updated all of my bundles to the latest version of `master`, instead of updating them to what's in the lockfile. It seems as though `:NeoBundleInstall` simply did the equivalent of `:NeoBundleUpdate` after first checking out the `master` branch on each repo.

My expectation is that `:NeoBundleInstall` would update all bundles to match exactly what's in my `NeoBundle.lock`, and that only `:NeoBundleUpdate` would be able to update bundles to a newer version.

**Comment by Shougo** [comment]
Fixed.

**Comment by rcmdnk** [comment]
Is this [master picking](https://github.com/Shougo/neobundle.vim/commit/508db1afe01c703149ba045bedc6baae6f90890d) really necessary to fix this problem?

It was changed to `HEAD` to be able to use repositories which have main branch which is not named as `master` a year ago.

If it should be `master`, I may need to change my plugins' branch name, or use branch name option in **.vimrc**.

**Comment by Shougo** [comment]
@rcmdnk This feature is needed.  Because, if you use locked revision, the repository is in detached state.
So, it is cannot be updated.
To fix the problem, neobundle must checkout master branch.  I don't know other solutions.
You should add master branch in the repository.

**Comment by rcmdnk** [comment]
Thanks for the answer.
I see, then I will update my plugin to use `master` as a main branch.
